import { createParticipant, logout, setParticipantActive } from "@/app/actions";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{created?:string}> }) {
  const admin = await requireUser("admin");
  const rows = (await db().execute(`SELECT u.id,u.login_id,u.condition_code,u.active,u.created_at,s.status,s.started_at,s.submitted_at,s.completion_seconds,s.final_word_count,
    (SELECT count(*) FROM interactions i WHERE i.participant_id=u.id) interactions,
    (SELECT count(*) FROM drafts d WHERE d.participant_id=u.id) drafts
    FROM users u LEFT JOIN studies s ON s.participant_id=u.id WHERE u.role='participant' ORDER BY u.created_at DESC`)).rows;
  const complete = rows.filter(r=>r.status==="completed").length;
  return <main className="app-shell"><header className="topbar"><div><strong>Auraly Research Console</strong><span>Signed in as {admin.loginId}</span></div><form action={logout}><button className="link-button">Sign out</button></form></header>
    <section className="admin-heading"><div><p className="eyebrow">RESEARCHER ACCESS</p><h1>Study overview</h1><p>Participant accounts are anonymous. Passwords are irreversibly hashed and cannot be viewed.</p></div><div className="stats"><span><b>{rows.length}</b>participants</span><span><b>{complete}</b>completed</span><span><b>{rows.length-complete}</b>remaining</span></div></section>
    {(await searchParams).created&&<div className="success-banner">Participant account created.</div>}
    <section className="panel"><div className="section-head"><div><h2>Create participant account</h2><p className="muted">Give the generated credentials to exactly one participant using a separate secure channel.</p></div></div><form action={createParticipant} className="inline-form"><label>Login ID<input name="loginId" placeholder="P001" pattern="P[A-Za-z0-9_-]{2,20}" required/></label><label>Temporary password<input name="password" type="password" minLength={10} required/></label><label>Assigned condition<select name="condition"><option value="A">A · General AI</option><option value="B">B · Prompt construction</option><option value="C">C · Prompt + scaffold</option></select></label><button className="primary">Create account</button></form></section>
    <section className="panel"><div className="section-head"><div><h2>Participant progress</h2><p className="muted">Condition assignments cannot be changed after account creation, protecting experimental integrity.</p></div><div className="export-links"><a href="/api/admin/export?format=csv">Export CSV</a><a href="/api/admin/export?format=json">Export JSON</a></div></div><div className="table-wrap"><table><thead><tr><th>ID</th><th>Condition</th><th>Status</th><th>Started</th><th>Submitted</th><th>Time</th><th>Words</th><th>AI uses</th><th>Drafts</th><th>Access</th></tr></thead><tbody>{rows.map(r=><tr key={String(r.id)}><td><strong>{String(r.login_id)}</strong></td><td>{String(r.condition_code)}</td><td><span className={`status ${r.status}`}>{String(r.status).replace("_"," ")}</span></td><td>{r.started_at?new Date(String(r.started_at)).toLocaleString():"—"}</td><td>{r.submitted_at?new Date(String(r.submitted_at)).toLocaleString():"—"}</td><td>{r.completion_seconds?`${Math.round(Number(r.completion_seconds)/60)} min`:"—"}</td><td>{Number(r.final_word_count)||"—"}</td><td>{Number(r.interactions)}</td><td>{Number(r.drafts)}</td><td><form action={setParticipantActive}><input type="hidden" name="userId" value={String(r.id)}/><input type="hidden" name="active" value={Number(r.active)?"0":"1"}/><button className="small-button">{Number(r.active)?"Disable":"Enable"}</button></form></td></tr>)}</tbody></table></div></section>
  </main>;
}
